name: On Plugin Release

on: repository_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: echo debug info
      run: |
        echo On Plugin Release!,
        echo "Go version: $(go version)",
        echo $(pwd),
        echo $(ls),
        echo "Git ref: ${{ github.ref }}",
        echo "Event type: ${{ github.event.action }}",
        echo "Event payload: ${{ toJson(github.event.client_payload) }}"
        echo "Event path: ${{github.event_path}}"
