name: On Plugin Release

on: repository_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: echo debug info
      run: |
        echo On Plugin Release!,
        echo $(pwd),
        echo $(ls),
        echo "Git ref: ${{ github.ref }}",
        echo "Event type: ${{ github.event.event_type }}",
        echo "Event: ${{ github.event.client_payload.foo }}",
        echo "payload: ${{ toJson(github.event.client_payload) }}"
        echo "payload: ${{ toJson(github.event) }}"
        echo "Event path: ${{github.event_path}}"
