name: On Plugin Release

on: repository_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: echo debug info
      run: |
        echo On Plugin Release!,
        echo $(pwd),
        echo $(ls),
        echo Git ref: ${{github.ref}},
        echo Event: ${{github.event}},
        echo Event path: ${{github.event_path}}
